name: Auto publish

on:
  push:
    paths:
      - 'info.json' # Triggers only if the mod info file is updated
    branches:
      - infinite_storage

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: get version
      id: version
      uses: notiz-dev/github-action-json-property@release
      with:
        path: 'info.json'
        prop_path: 'version'
    - name: get factorio_version
      id: factorio_version
      uses: notiz-dev/github-action-json-property@release
      with:
        path: 'info.json'
        prop_path: 'factorio_version'
    - name: get mod name
      id: mod_name
      uses: notiz-dev/github-action-json-property@release
      with:
        path: 'info.json'
        prop_path: 'name'
    - uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: "5.4.6"
    - uses: leafo/gh-actions-luarocks@v4
      with:
        luarocksVersion: "3.9.2"
    - name: install candran
      run: luarocks install candran
    - name: install lpeg
      run: luarocks install lpeg
    - name: install 7z, jq
      run: sudo apt install p7zip-full jq -y
    - name: Candran to Lua
      run: lua ./.scripts/CandranToLua.lua
    - name: Zip mod
      run: bash ./.scripts/zip_mod.sh
    - name: Upload the mod on mods.factorio.com
      env:
        FACTORIO_MOD_API_KEY: ${{ secrets.FACTORIO_MOD_API_KEY }}
      run: bash ./.scripts/upload.sh
    - uses: marvinpinto/action-automatic-releases@latest
      id: aar
      with:
        automatic_release_tag: "${{steps.version.outputs.prop}}"
        title: "For factorio ${{steps.factorio_version.outputs.prop}}"
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          ./${{steps.mod_name.outputs.prop}}_${{steps.version.outputs.prop}}.zip